sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t chitrakanthreddy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chitrakanthreddy/docker-react npm run test
